// Dev: the scripted demo chats played by lib/engine/demo.ts (start one from /dev). Edit freely.
// Each line is "Riff: <nudge>", "<a.name>: <message>" or "<b.name>: <message>", played in order about 2.5 s apart.
// You sit in seat A (a's lines are sent as you); the bot plays b. A nudge's answers are whatever comes before the
// next "Riff:" line (or its timer running out). Scoring, Moment Spotlight, the chat summary and the coach are real.

export type DemoScript = {
  id: string;
  title: string;
  about: string; // what it's for, shown on /dev
  a: { name: string; interests: string[] };
  b: { name: string; interests: string[] };
  lines: string[];
};

export const DEMO_SCRIPTS: DemoScript[] = [
  {
    id: "clicks",
    title: "1 · It clicks",
    about: "Specific answers, follow-ups and a running joke. Expect high quality + connection and a full Moment Spotlight.",
    a: { name: "Sam", interests: ["gaming", "movies", "cooking"] },
    b: { name: "Maya", interests: ["anime", "food", "travel"] },
    lines: [
      "Riff: Say hi! Your name and where you're from",
      "Sam: hey! sam, grew up in savannah, now in atlanta for school",
      "Maya: maya! from houston. savannah is so pretty, all the moss trees",
      "Sam: the moss is great until it falls on you lol",
      "Riff: What's something you've been weirdly into lately?",
      "Maya: making ramen from scratch. the broth takes 12 hours and my roommates hate the smell",
      "Sam: wait 12 hours?? i made tonkotsu once and gave up at hour 4 and just ate instant",
      "Maya: hour 4 is the danger zone, that's when it smells like a barn",
      "Sam: THAT'S what that was. i thought i ruined it",
      "Riff: Hot take: which movie is way better than people say?",
      "Sam: the matrix resurrections. it's a movie about making a sequel you don't want to make and i respect that",
      "Maya: ok that's actually a smart take. mine is speed racer, it's basically a live action anime",
      "Sam: speed racer is so good. the colors alone",
      "Maya: finally someone gets it",
      "Riff: You get one hour anywhere in the world. Where and what first?",
      "Maya: tokyo, a 6 seat ramen counter at 2am. research for the 12 hour broth",
      "Sam: kyoto for the food market, but honestly i'd follow you to the ramen counter so you can explain hour 4",
      "Maya: deal. hour 4 tour guide",
      "Riff: What's a small thing that made you really happy recently?",
      "Sam: my little brother beat me at smash for the first time and did a full lap around the house",
      "Maya: that's adorable. did you let him win",
      "Sam: absolutely not, he earned it and i'm still mad",
      "Maya: my grandma texted me a photo of her garden with 'look' and nothing else and i've been smiling since",
      "Sam: the 'look' text is elite grandma behavior",
    ],
  },
  {
    id: "flat",
    title: "2 · Falls flat",
    about: "You give one-word answers and miss references (Roman Empire, Kendall Roy, Grimace shake). Expect low scores, 'died' topics and coach misses.",
    a: { name: "Sam", interests: ["gaming", "movies", "cooking"] },
    b: { name: "Jordan", interests: ["sports", "memes", "gaming"] },
    lines: [
      "Riff: Say hi! Your name and where you're from",
      "Jordan: yo jordan here, from chicago",
      "Sam: hey",
      "Jordan: where you from",
      "Sam: atlanta",
      "Riff: How often do you think about the Roman Empire?",
      "Jordan: every single day man. that trend exposed all of us",
      "Sam: what trend",
      "Jordan: the one where you ask guys how often they think about the roman empire lol",
      "Sam: oh. idk",
      "Riff: Which TV character are you most like, honestly?",
      "Jordan: kendall roy. failing upward with total confidence",
      "Sam: who's that",
      "Jordan: succession?? the rapping at the party??",
      "Sam: haven't seen it",
      "Jordan: ok fair",
      "Riff: What's the last thing you tried just because the internet told you to?",
      "Jordan: the grimace shake. regret nothing",
      "Sam: the what",
      "Jordan: the purple mcdonalds shake, everyone was filming themselves 'dying' after drinking it",
      "Sam: weird",
      "Riff: Best game you've played this year?",
      "Jordan: balatro ate my whole semester",
      "Sam: elden ring i guess",
      "Jordan: dlc or base game",
      "Sam: base",
    ],
  },
  {
    id: "comeback",
    title: "3 · Slow start, comeback",
    about: "You start behind, then a gaming nudge lands on your turf and you open up with callbacks. Mixed scores, one miss (the Stanley cup craze).",
    a: { name: "Sam", interests: ["gaming", "movies", "cooking"] },
    b: { name: "Priya", interests: ["books", "art", "music"] },
    lines: [
      "Riff: Say hi! Your name and where you're from",
      "Priya: hi! priya, from jersey but i've lived in atlanta since i was 10 so i claim both",
      "Sam: hey sam, atlanta",
      "Priya: a local! rare",
      "Riff: What's on your playlist on repeat right now?",
      "Priya: a lot of phoebe bridgers and whatever my sister sends me. mostly sad songs i walk to class to",
      "Sam: idk just random stuff",
      "Priya: fair lol",
      "Riff: What's a trend you don't get?",
      "Priya: the stanley cup thing. people fighting in target over a water bottle",
      "Sam: the hockey trophy?",
      "Priya: no lol the giant tumbler cups, people were collecting them in every color",
      "Sam: oh ok",
      "Riff: What game would you want to live inside for a week?",
      "Sam: stardew valley no question. i'd fish all day and ignore every villager except linus",
      "Priya: i've never played but i know it's the cozy farming one. why linus",
      "Sam: he lives in a tent and is the only person who's honest about everything. also he'd give me the best fishing spots",
      "Priya: a tent man with fishing secrets. i see the appeal",
      "Sam: and it'd have better background music than the sad walk-to-class playlist",
      "Priya: HEY. ok fair, stardew's soundtrack is actually lovely, my sister plays it to study",
      "Riff: What's something you could teach someone in 5 minutes?",
      "Sam: how to make a perfect omelette. low heat, keep stirring, take it off before it looks done",
      "Priya: i always overcook them, i need this",
      "Sam: 5 minutes, i'll throw in a stardew fishing tutorial for free",
      "Priya: how to draw a face that doesn't look like a potato. i'll trade you",
      "Sam: deal, my faces are all potatoes",
    ],
  },
];
