// Seeded people for search (SPEC §7 Discovery): always in the queue in browse mode. Inviting one seats the bot as them.
// [name, school, 3 interests, bio]. Ids are "seed:<index>"; keep the order stable.

export type Persona = { id: string; name: string; school: string; interests: string[]; bio: string };

const RAW: [string, string, string, string][] = [
  ["Maya", "Georgia Tech", "anime, ramen, solo travel", "Will rank every Studio Ghibli movie if you let me"],
  ["Jordan", "Georgia Tech", "hawks basketball, memes, fortnite", "Courtside energy, couch budget"],
  ["Priya", "Emory", "fantasy books, watercolor, indie music", "Currently 40 pages into three different books"],
  ["Leo", "Georgia State", "lifting, hiking, meal prep", "Chicken, rice, and a trail on Sundays"],
  ["Sam", "Georgia Tech", "mechanical keyboards, valorant, sci-fi movies", "Built my own keyboard, won't shut up about it"],
  ["Ava", "SCAD Atlanta", "thrifting, fashion design, jazz", "Everything I wear is secondhand and I'm proud of it"],
  ["Marcus", "Morehouse", "debate, hip hop, chess", "Will argue either side just for fun"],
  ["Zoe", "Spelman", "poetry, natural hair, podcasts", "Spoken word on Thursdays, true crime on loop"],
  ["Ethan", "UGA", "college football, bbq, country music", "Go Dawgs, and yes I have a smoker"],
  ["Lily", "Emory", "k-pop, baking, skincare", "My sourdough starter has a name"],
  ["Noah", "Georgia Tech", "robotics, rock climbing, coffee", "Ships robots by day, boulders V5 by night"],
  ["Isabella", "Georgia State", "salsa dancing, telenovelas, cooking", "Abuela's recipes, my own twist"],
  ["Aiden", "Kennesaw State", "skateboarding, punk rock, film photography", "Shoots on a camera older than me"],
  ["Chloe", "SCAD Atlanta", "animation, cats, horror movies", "Draws my cat as horror movie villains"],
  ["Dev", "Georgia Tech", "cricket, startups, bollywood", "Has three side projects and one finished"],
  ["Hannah", "UGA", "horses, taylor swift, journaling", "Every era, every bracelet"],
  ["Tyler", "Georgia Tech", "formula 1, sim racing, cars", "Strong opinions about tire strategy"],
  ["Mia", "Emory", "pre-med, marathons, true crime", "Runs 20 miles, then studies for the MCAT"],
  ["Jalen", "Clark Atlanta", "music production, sneakers, basketball", "Makes beats in the dorm at 2 a.m."],
  ["Sofia", "Georgia State", "photography, street food, travel", "Eats her way through every city first"],
  ["Ryan", "Georgia Tech", "dnd, board games, fantasy", "Dungeon master, ruthless but fair"],
  ["Emma", "Emory", "musical theater, singing, broadway", "Knows every word to Hamilton, sorry"],
  ["Kevin", "Georgia Tech", "anime, gym, cooking", "Recreates anime food, results vary"],
  ["Nia", "Spelman", "entrepreneurship, fashion, gospel", "Runs a small jewelry business from my dorm"],
  ["Lucas", "UGA", "fishing, outdoors, country music", "Happiest on a lake at 6 a.m."],
  ["Grace", "Agnes Scott", "birdwatching, knitting, folk music", "Can name a bird by its song"],
  ["Omar", "Georgia State", "soccer, fifa, shawarma", "Arsenal fan, it's been hard"],
  ["Ella", "SCAD Atlanta", "interior design, plants, lo-fi", "Seventeen plants, zero dead (so far)"],
  ["Mason", "Georgia Tech", "cybersecurity, ctfs, techno", "Breaks things legally"],
  ["Aaliyah", "Clark Atlanta", "dance, r&b, reality tv", "Choreographs to every Beyoncé song"],
  ["Ben", "Emory", "philosophy, coffee, jazz", "Asks 'but why' until everyone leaves"],
  ["Harper", "Georgia Tech", "aerospace, stargazing, sci-fi books", "Wants to be on Mars by 40"],
  ["Diego", "Georgia State", "boxing, reggaeton, tacos", "Tacos are a personality trait"],
  ["Ruby", "SCAD Atlanta", "tattoo art, metal music, comics", "Sketchbook full of tattoo ideas"],
  ["Caleb", "Kennesaw State", "hunting, trucks, gospel", "Sunday service and a Chevy"],
  ["Ananya", "Georgia Tech", "classical dance, coding, chai", "Bharatanatyam and Python"],
  ["Owen", "UGA", "golf, podcasts, fantasy football", "Commissioner of three fantasy leagues"],
  ["Layla", "Emory", "public health, yoga, travel", "Has a spreadsheet for every trip"],
  ["Chris", "Georgia Tech", "pokemon, speedrunning, retro games", "Beat Pokémon Red in under two hours"],
  ["Jasmine", "Spelman", "law, debate, true crime", "Future lawyer, current courtroom-drama addict"],
  ["Ahmed", "Georgia State", "engineering, soccer, calligraphy", "Arabic calligraphy between problem sets"],
  ["Sadie", "Agnes Scott", "tarot, astrology, vinyl", "Reads your chart before your résumé"],
  ["Derek", "Georgia Tech", "powerlifting, anime, protein recipes", "Deadlifts and One Piece"],
  ["Camila", "Emory", "latin pop, volunteering, dogs", "Fosters dogs, keeps getting attached"],
  ["Julian", "Morehouse", "jazz piano, history, suits", "Plays piano like it's 1959"],
  ["Riley", "Kennesaw State", "camping, guitar, campfire cooking", "Brings a guitar to every campfire"],
  ["Nora", "Georgia Tech", "urban planning, cycling, transit", "Will talk about MARTA for hours"],
  ["Andre", "Clark Atlanta", "spoken word, activism, soul food", "Writes poems on the train"],
  ["Kayla", "UGA", "sorority life, brunch, reality tv", "Brunch is a sport and I'm varsity"],
  ["Ivan", "Georgia Tech", "chess, math puzzles, piano", "1900 on chess.com, humble about it (not really)"],
  ["Tessa", "SCAD Atlanta", "film making, horror, thrifting", "Making a short film with zero budget"],
  ["Brandon", "Georgia State", "stand-up comedy, improv, memes", "Tells jokes to cope, mostly works"],
  ["Mei", "Emory", "bubble tea, k-dramas, badminton", "Rates every boba shop in Atlanta"],
  ["Elijah", "Morehouse", "track, gospel, sneakers", "400m runner, sneakerhead"],
  ["Paige", "Kennesaw State", "equestrian, country music, baking", "Pies for every occasion"],
  ["Victor", "Georgia Tech", "ai, poker, espresso", "Trains models, reads poker tells"],
  ["Alyssa", "Georgia State", "nursing, gym, cheer", "Twelve-hour shifts and still makes leg day"],
  ["Sebastian", "Emory", "tennis, wine tasting, travel", "Plays tennis badly with great confidence"],
  ["Tiana", "Spelman", "biology, natural hair, anime", "STEM girlie with a Naruto phase that never ended"],
  ["Cole", "UGA", "hunting, college football, bbq", "Brisket is a 14-hour commitment"],
  ["Rosa", "Georgia State", "painting, mariachi, gardening", "Grows her own chiles"],
  ["Adam", "Georgia Tech", "hackathons, energy drinks, linux", "Uses Arch, btw"],
  ["Imani", "Clark Atlanta", "fashion, afrobeats, photography", "Styles photoshoots for friends"],
  ["Jake", "Kennesaw State", "baseball, fishing, video games", "Braves fan through thick and thin"],
  ["Olivia", "Emory", "neuroscience, running, podcasts", "Asks what your dreams mean, scientifically"],
  ["Hiro", "Georgia Tech", "anime, game dev, japanese food", "Making an indie game about a cat samurai"],
  ["Brianna", "Spelman", "psychology, journaling, r&b", "Will psychoanalyze your playlist"],
  ["Zach", "UGA", "frisbee, hiking, hammocks", "Hangs a hammock anywhere with two trees"],
  ["Esther", "Agnes Scott", "theology, choir, baking", "Choir soprano, bakes for the whole hall"],
  ["Malik", "Morehouse", "business, basketball, podcasts", "Starting a podcast about starting podcasts"],
  ["Anna", "Georgia Tech", "biomed, ballet, true crime", "Ballet for twelve years, lab for three"],
  ["Tony", "Georgia State", "cooking, italian food, soccer", "Nonna's sauce, no jar, ever"],
  ["Lena", "SCAD Atlanta", "graphic design, typography, coffee", "Judges menus by their fonts"],
  ["Kai", "Georgia Tech", "surfing, climate, photography", "Landlocked surfer, climate nerd"],
  ["Destiny", "Clark Atlanta", "gospel, poetry, mentoring", "Mentors middle schoolers on weekends"],
  ["Luke", "Kennesaw State", "disc golf, craft soda, indie games", "Disc golf is a real sport, fight me"],
  ["Farah", "Emory", "global health, hijabi fashion, baking", "Cupcakes and public health policy"],
  ["Nathan", "Georgia Tech", "quantum physics, jazz, bouldering", "Explains quantum with pizza analogies"],
  ["Gabby", "Georgia State", "musical theater, tiktok, dance", "Viral once, never recovered"],
  ["Isaiah", "Morehouse", "film, screenwriting, jazz", "Writing the next great Atlanta movie"],
  ["Megan", "UGA", "volleyball, beach trips, country music", "Beach volleyball summers"],
  ["Arjun", "Georgia Tech", "cricket, finance, bollywood dance", "Quant by day, bhangra by night"],
  ["Sienna", "SCAD Atlanta", "fashion photography, vintage, jazz", "Collects vintage cameras"],
  ["Trey", "Clark Atlanta", "basketball, sneakers, rap", "Two-way player, no defense"],
  ["Claire", "Emory", "creative writing, tea, cats", "Writing a novel, chapter one, forever"],
  ["Jin", "Georgia Tech", "k-pop dance, esports, fried chicken", "Dances in the student center"],
  ["Monique", "Spelman", "economics, hip hop, travel", "Wants to fix the economy, starting with my budget"],
  ["Evan", "Kennesaw State", "rock music, drums, skateboarding", "Drummer, neighbors hate me"],
  ["Lucia", "Georgia State", "social work, salsa, telenovelas", "Cries at every telenovela finale"],
  ["Max", "Georgia Tech", "3d printing, lego, sci-fi", "Prints spare parts for everyone's stuff"],
  ["Jada", "Clark Atlanta", "nails, r&b, reality tv", "Does her own nails, takes clients"],
  ["Henry", "Emory", "history, board games, podcasts", "Knows a weird fact about every president"],
  ["Rachel", "UGA", "running, pilates, smoothies", "Sunrise runs, smoothie after"],
  ["Tariq", "Georgia State", "photography, soccer, hip hop", "Shoots local soccer games"],
  ["Bella", "SCAD Atlanta", "illustration, cozy games, tea", "Stardew Valley is my therapy"],
  ["Darius", "Morehouse", "politics, debate, jazz", "Debate team captain, jazz on repeat"],
  ["Quinn", "Georgia Tech", "urban gardening, sustainability, cycling", "Grows tomatoes on the dorm roof"],
  ["Yara", "Emory", "arabic poetry, cooking, travel", "Hosts dinner parties with too much food"],
  ["Cody", "Kennesaw State", "wrestling, anime, gaming", "Watches wrestling unironically"],
  ["Wren", "Agnes Scott", "rock climbing, sci-fi books, thai food", "Reads Le Guin between climbs"],
];

export const PERSONAS: Persona[] = RAW.map(([name, school, interests, bio], i) => ({
  id: `seed:${i}`,
  name,
  school,
  interests: interests.split(", "),
  bio,
}));
