// Seeded people for search (SPEC §7 Discovery): always in the queue in browse mode. Inviting one seats the bot as them.
// [name, school, 3 interests, bio]. Ids are "seed:<index>"; keep the order stable.

export type Persona = { id: string; name: string; school: string; interests: string[]; bio: string };

const RAW: [string, string, string, string][] = [
  ["Maya", "Georgia Tech", "anime, ramen, solo travel", "Will rank every Studio Ghibli movie if you let me"],
  ["Jordan", "Georgia Tech", "hawks basketball, memes, fortnite", "Courtside energy, couch budget"],
  ["Priya", "Emory", "fantasy books, watercolor, indie music", "Currently 40 pages into three different books"],
  ["Leo", "Georgia State", "lifting, hiking, meal prep", "Chicken, rice, and a trail on Sundays"],
  ["Sam", "Georgia Tech", "mechanical keyboards, valorant, sci-fi movies", "Built my own keyboard, won't shut up about it"],
  ["Ava", "SCAD Atlanta", "thrifting, fashion design, jazz", "Everything I wear is secondhand and I'm proud of it"],
  ["Marcus", "Morehouse", "debate, hip hop, chess", "Will argue either side just for fun"],
  ["Zoe", "Spelman", "poetry, natural hair, podcasts", "Spoken word on Thursdays, true crime on loop"],
  ["Ethan", "UGA", "college football, bbq, country music", "Go Dawgs, and yes I have a smoker"],
  ["Lily", "Emory", "k-pop, baking, skincare", "My sourdough starter has a name"],
  ["Noah", "Georgia Tech", "robotics, rock climbing, coffee", "Ships robots by day, boulders V5 by night"],
  ["Isabella", "Georgia State", "salsa dancing, telenovelas, cooking", "Abuela's recipes, my own twist"],
  ["Aiden", "Kennesaw State", "skateboarding, punk rock, film photography", "Shoots on a camera older than me"],
  ["Chloe", "SCAD Atlanta", "animation, cats, horror movies", "Draws my cat as horror movie villains"],
  ["Dev", "Georgia Tech", "cricket, startups, bollywood", "Has three side projects and one finished"],
  ["Hannah", "UGA", "horses, taylor swift, journaling", "Every era, every bracelet"],
  ["Tyler", "Georgia Tech", "formula 1, sim racing, cars", "Strong opinions about tire strategy"],
  ["Mia", "Emory", "pre-med, marathons, true crime", "Runs 20 miles, then studies for the MCAT"],
  ["Jalen", "Clark Atlanta", "music production, sneakers, basketball", "Makes beats in the dorm at 2 a.m."],
  ["Sofia", "Georgia State", "photography, street food, travel", "Eats her way through every city first"],
  ["Ryan", "Georgia Tech", "dnd, board games, fantasy", "Dungeon master, ruthless but fair"],
  ["Emma", "Emory", "musical theater, singing, broadway", "Knows every word to Hamilton, sorry"],
  ["Kevin", "Georgia Tech", "anime, gym, cooking", "Recreates anime food, results vary"],
  ["Nia", "Spelman", "entrepreneurship, fashion, gospel", "Runs a small jewelry business from my dorm"],
  ["Lucas", "UGA", "fishing, outdoors, country music", "Happiest on a lake at 6 a.m."],
  ["Grace", "Agnes Scott", "birdwatching, knitting, folk music", "Can name a bird by its song"],
  ["Omar", "Georgia State", "soccer, fifa, shawarma", "Arsenal fan, it's been hard"],
  ["Ella", "SCAD Atlanta", "interior design, plants, lo-fi", "Seventeen plants, zero dead (so far)"],
  ["Mason", "Georgia Tech", "cybersecurity, ctfs, techno", "Breaks things legally"],
  ["Aaliyah", "Clark Atlanta", "dance, r&b, reality tv", "Choreographs to every Beyoncé song"],
  ["Ben", "Emory", "philosophy, coffee, jazz", "Asks 'but why' until everyone leaves"],
  ["Harper", "Georgia Tech", "aerospace, stargazing, sci-fi books", "Wants to be on Mars by 40"],
  ["Diego", "Georgia State", "boxing, reggaeton, tacos", "Tacos are a personality trait"],
  ["Ruby", "SCAD Atlanta", "tattoo art, metal music, comics", "Sketchbook full of tattoo ideas"],
  ["Caleb", "Kennesaw State", "hunting, trucks, gospel", "Sunday service and a Chevy"],
  ["Ananya", "Georgia Tech", "classical dance, coding, chai", "Bharatanatyam and Python"],
  ["Owen", "UGA", "golf, podcasts, fantasy football", "Commissioner of three fantasy leagues"],
  ["Layla", "Emory", "public health, yoga, travel", "Has a spreadsheet for every trip"],
  ["Chris", "Georgia Tech", "pokemon, speedrunning, retro games", "Beat Pokémon Red in under two hours"],
  ["Jasmine", "Spelman", "law, debate, true crime", "Future lawyer, current courtroom-drama addict"],
  ["Ahmed", "Georgia State", "engineering, soccer, calligraphy", "Arabic calligraphy between problem sets"],
  ["Sadie", "Agnes Scott", "tarot, astrology, vinyl", "Reads your chart before your résumé"],
  ["Derek", "Georgia Tech", "powerlifting, anime, protein recipes", "Deadlifts and One Piece"],
  ["Camila", "Emory", "latin pop, volunteering, dogs", "Fosters dogs, keeps getting attached"],
  ["Julian", "Morehouse", "jazz piano, history, suits", "Plays piano like it's 1959"],
  ["Riley", "Kennesaw State", "camping, guitar, campfire cooking", "Brings a guitar to every campfire"],
  ["Nora", "Georgia Tech", "urban planning, cycling, transit", "Will talk about MARTA for hours"],
  ["Andre", "Clark Atlanta", "spoken word, activism, soul food", "Writes poems on the train"],
  ["Kayla", "UGA", "sorority life, brunch, reality tv", "Brunch is a sport and I'm varsity"],
  ["Ivan", "Georgia Tech", "chess, math puzzles, piano", "1900 on chess.com, humble about it (not really)"],
  ["Tessa", "SCAD Atlanta", "film making, horror, thrifting", "Making a short film with zero budget"],
  ["Brandon", "Georgia State", "stand-up comedy, improv, memes", "Tells jokes to cope, mostly works"],
  ["Mei", "Emory", "bubble tea, k-dramas, badminton", "Rates every boba shop in Atlanta"],
  ["Elijah", "Morehouse", "track, gospel, sneakers", "400m runner, sneakerhead"],
  ["Paige", "Kennesaw State", "equestrian, country music, baking", "Pies for every occasion"],
  ["Victor", "Georgia Tech", "ai, poker, espresso", "Trains models, reads poker tells"],
  ["Alyssa", "Georgia State", "nursing, gym, cheer", "Twelve-hour shifts and still makes leg day"],
  ["Sebastian", "Emory", "tennis, wine tasting, travel", "Plays tennis badly with great confidence"],
  ["Tiana", "Spelman", "biology, natural hair, anime", "STEM girlie with a Naruto phase that never ended"],
  ["Cole", "UGA", "hunting, college football, bbq", "Brisket is a 14-hour commitment"],
  ["Rosa", "Georgia State", "painting, mariachi, gardening", "Grows her own chiles"],
  ["Adam", "Georgia Tech", "hackathons, energy drinks, linux", "Uses Arch, btw"],
  ["Imani", "Clark Atlanta", "fashion, afrobeats, photography", "Styles photoshoots for friends"],
  ["Jake", "Kennesaw State", "baseball, fishing, video games", "Braves fan through thick and thin"],
  ["Olivia", "Emory", "neuroscience, running, podcasts", "Asks what your dreams mean, scientifically"],
  ["Hiro", "Georgia Tech", "anime, game dev, japanese food", "Making an indie game about a cat samurai"],
  ["Brianna", "Spelman", "psychology, journaling, r&b", "Will psychoanalyze your playlist"],
  ["Zach", "UGA", "frisbee, hiking, hammocks", "Hangs a hammock anywhere with two trees"],
  ["Esther", "Agnes Scott", "theology, choir, baking", "Choir soprano, bakes for the whole hall"],
  ["Malik", "Morehouse", "business, basketball, podcasts", "Starting a podcast about starting podcasts"],
  ["Anna", "Georgia Tech", "biomed, ballet, true crime", "Ballet for twelve years, lab for three"],
  ["Tony", "Georgia State", "cooking, italian food, soccer", "Nonna's sauce, no jar, ever"],
  ["Lena", "SCAD Atlanta", "graphic design, typography, coffee", "Judges menus by their fonts"],
  ["Kai", "Georgia Tech", "surfing, climate, photography", "Landlocked surfer, climate nerd"],
  ["Destiny", "Clark Atlanta", "gospel, poetry, mentoring", "Mentors middle schoolers on weekends"],
  ["Luke", "Kennesaw State", "disc golf, craft soda, indie games", "Disc golf is a real sport, fight me"],
  ["Farah", "Emory", "global health, hijabi fashion, baking", "Cupcakes and public health policy"],
  ["Nathan", "Georgia Tech", "quantum physics, jazz, bouldering", "Explains quantum with pizza analogies"],
  ["Gabby", "Georgia State", "musical theater, tiktok, dance", "Viral once, never recovered"],
  ["Isaiah", "Morehouse", "film, screenwriting, jazz", "Writing the next great Atlanta movie"],
  ["Megan", "UGA", "volleyball, beach trips, country music", "Beach volleyball summers"],
  ["Arjun", "Georgia Tech", "cricket, finance, bollywood dance", "Quant by day, bhangra by night"],
  ["Sienna", "SCAD Atlanta", "fashion photography, vintage, jazz", "Collects vintage cameras"],
  ["Trey", "Clark Atlanta", "basketball, sneakers, rap", "Two-way player, no defense"],
  ["Claire", "Emory", "creative writing, tea, cats", "Writing a novel, chapter one, forever"],
  ["Jin", "Georgia Tech", "k-pop dance, esports, fried chicken", "Dances in the student center"],
  ["Monique", "Spelman", "economics, hip hop, travel", "Wants to fix the economy, starting with my budget"],
  ["Evan", "Kennesaw State", "rock music, drums, skateboarding", "Drummer, neighbors hate me"],
  ["Lucia", "Georgia State", "social work, salsa, telenovelas", "Cries at every telenovela finale"],
  ["Max", "Georgia Tech", "3d printing, lego, sci-fi", "Prints spare parts for everyone's stuff"],
  ["Jada", "Clark Atlanta", "nails, r&b, reality tv", "Does her own nails, takes clients"],
  ["Henry", "Emory", "history, board games, podcasts", "Knows a weird fact about every president"],
  ["Rachel", "UGA", "running, pilates, smoothies", "Sunrise runs, smoothie after"],
  ["Tariq", "Georgia State", "photography, soccer, hip hop", "Shoots local soccer games"],
  ["Bella", "SCAD Atlanta", "illustration, cozy games, tea", "Stardew Valley is my therapy"],
  ["Darius", "Morehouse", "politics, debate, jazz", "Debate team captain, jazz on repeat"],
  ["Quinn", "Georgia Tech", "urban gardening, sustainability, cycling", "Grows tomatoes on the dorm roof"],
  ["Yara", "Emory", "arabic poetry, cooking, travel", "Hosts dinner parties with too much food"],
  ["Cody", "Kennesaw State", "wrestling, anime, gaming", "Watches wrestling unironically"],
  ["Wren", "Agnes Scott", "rock climbing, sci-fi books, thai food", "Reads Le Guin between climbs"],
  ["Aria", "Georgia Tech", "elden ring, souls games, lofi", "Died to Malenia 200 times and counting"],
  ["Brooke", "UGA", "sorority life, tailgates, true crime", "Knows every Dateline episode by heart"],
  ["Carter", "Georgia State", "skateboarding, graffiti, hip hop", "Paints walls legally, mostly"],
  ["Dante", "Morehouse", "chess, philosophy, soul music", "Plays blitz between classes"],
  ["Eli", "Emory", "neuroscience, running, podcasts", "Training for my first marathon"],
  ["Fatima", "Georgia State", "henna art, baking, k-dramas", "Takes custom cake orders from my dorm"],
  ["Gavin", "Kennesaw State", "trucks, country music, fishing", "Will fix your car for a plate of wings"],
  ["Hailey", "UGA", "volleyball, iced coffee, taylor swift", "Setter on and off the court"],
  ["Ian", "Georgia Tech", "league of legends, anime, energy drinks", "Diamond in League, bronze in sleep"],
  ["Jenna", "Emory", "pre-med, yoga, smoothies", "Organic chem survivor"],
  ["Kofi", "Morehouse", "afrobeats, soccer, fashion", "Brings a speaker everywhere"],
  ["Lauren", "Agnes Scott", "poetry, vintage books, tea", "Owns 400 books and reads them all"],
  ["Miles", "Georgia Tech", "jazz trumpet, robotics, coffee", "Plays trumpet in the marching band"],
  ["Naomi", "Spelman", "natural hair, dance, church choir", "Choreographs for my dance team"],
  ["Oscar", "Georgia State", "soccer, fifa, mexican food", "FIFA ultimate team is a lifestyle"],
  ["Penelope", "SCAD Atlanta", "ceramics, plants, indie folk", "Throws pots, not shade"],
  ["Rafael", "Emory", "salsa dancing, economics, coffee", "Teaches salsa on Friday nights"],
  ["Selena", "Georgia State", "makeup, tiktok, bachata", "Beats faces for weddings on weekends"],
  ["Theo", "Georgia Tech", "zelda, game design, piano", "Plays every Zelda song by ear"],
  ["Uma", "Emory", "bharatanatyam, biology, chai", "Dancing since I was four"],
  ["Vince", "Kennesaw State", "mma, lifting, meal prep", "Trains jiu jitsu five days a week"],
  ["Willow", "Agnes Scott", "witchy stuff, tarot, herbal tea", "Will read your cards, no charge"],
  ["Xavier", "Clark Atlanta", "rap, sneakers, fashion", "Resells sneakers to pay rent"],
  ["Yusuf", "Georgia Tech", "cybersecurity, ctf, chess", "Breaks things for a living, legally"],
  ["Zara", "Spelman", "law, debate, podcasts", "Future civil rights attorney"],
  ["Amir", "Georgia State", "basketball, nba 2k, cooking", "2K MyTeam grinder"],
  ["Bianca", "SCAD Atlanta", "animation, disney, drawing", "Frame by frame, one coffee at a time"],
  ["Cameron", "UGA", "golf, finance, country music", "Wakes up at 5 for tee times"],
  ["Daisy", "Kennesaw State", "horses, rodeo, baking", "Barrel racer on weekends"],
  ["Emeka", "Georgia Tech", "electrical engineering, afrobeats, soccer", "Builds amps from scratch"],
  ["Fiona", "Emory", "irish dance, history, fantasy books", "Has read Lord of the Rings six times"],
  ["Grant", "UGA", "college football, hunting, bbq", "Tailgate grill master"],
  ["Hana", "Georgia Tech", "japanese, anime, bubble tea", "Learning Japanese one manga at a time"],
  ["Isaac", "Emory", "physics, chess, classical music", "Explains string theory at parties"],
  ["Jade", "SCAD Atlanta", "fashion design, thrifting, r&b", "Sews my own clothes"],
  ["Kenji", "Georgia Tech", "street fighter, fighting games, ramen", "Goes to local fighting game tournaments"],
  ["Leah", "Georgia State", "nursing, zumba, gospel", "Future ER nurse"],
  ["Mateo", "Kennesaw State", "soccer, reggaeton, fifa", "Captain of the intramural team"],
  ["Nadia", "Emory", "arabic, public policy, coffee", "Runs the Middle East students club"],
  ["Oliver", "Georgia Tech", "minecraft, redstone, lego", "Built a working computer in Minecraft"],
  ["Phoebe", "Agnes Scott", "birdwatching, hiking, journaling", "Has a life list of 212 birds"],
  ["Reggie", "Clark Atlanta", "marching band, drumline, rap", "Snare drum section leader"],
  ["Sana", "Georgia Tech", "machine learning, badminton, bollywood", "Knows every Shah Rukh Khan movie"],
  ["Travis", "Kennesaw State", "dirt bikes, country music, camping", "Rides trails every weekend"],
  ["Valeria", "Georgia State", "telenovelas, cooking, salsa music", "My abuela's recipes, my way"],
  ["Wes", "UGA", "fly fishing, bluegrass, hiking", "Plays banjo badly but proudly"],
  ["Ximena", "Emory", "spanish literature, poetry, cafes", "Writes poems in two languages"],
  ["Yasmin", "Georgia State", "fashion, instagram, travel", "Plans trips I can't afford yet"],
  ["Zion", "Morehouse", "basketball, sneakers, gospel", "Pickup hoops every morning at 6"],
  ["Abby", "UGA", "sorority life, pilates, brunch", "Brunch is a personality trait"],
  ["Blake", "Georgia Tech", "rocket league, cars, energy drinks", "Champion rank, zero regrets"],
  ["Cierra", "Spelman", "biology, natural hair, r&b", "Future dermatologist"],
  ["Dominic", "Kennesaw State", "baseball, call of duty, grilling", "Pitcher with a mean slider"],
  ["Erin", "Agnes Scott", "musicals, choir, baking", "Belts Wicked in the shower"],
  ["Felix", "Georgia Tech", "3d printing, drones, sci-fi", "Prints parts for my own drones"],
  ["Gia", "SCAD Atlanta", "photography, fashion, vintage", "Shoots film for local brands"],
  ["Hunter", "UGA", "duck hunting, college football, country music", "Up before the sun in duck season"],
  ["Iris", "Emory", "art history, museums, wine", "Knows too much about the Renaissance"],
  ["Jamal", "Clark Atlanta", "music production, hip hop, video games", "Makes beats between Madden games"],
  ["Kira", "Georgia Tech", "valorant, twitch streaming, cats", "Streams three nights a week"],
  ["Logan", "Kennesaw State", "snowboarding, skateboarding, punk rock", "Snowboards one week a year, dreams about it all year"],
  ["Maddie", "UGA", "equestrian, country music, dogs", "Three dogs, one horse, no regrets"],
  ["Nico", "Georgia State", "dj, house music, sneakers", "Spins at campus parties"],
  ["Opal", "SCAD Atlanta", "jewelry making, crystals, indie music", "Makes rings out of old spoons"],
  ["Parker", "Georgia Tech", "rock climbing, startups, coffee", "Pitching a startup every week"],
  ["Rhea", "Emory", "debate, politics, podcasts", "Model UN chair"],
  ["Simone", "Spelman", "ballet, french, classical music", "Danced ballet for 15 years"],
  ["Tomas", "Georgia State", "cycling, coffee, photography", "Rides to class, rain or shine"],
  ["Vivian", "Agnes Scott", "fantasy books, dnd, knitting", "Knits scarves for my DnD party"],
  ["Warren", "Morehouse", "economics, golf, jazz", "Future finance bro, jazz head"],
  ["Aisha", "Georgia State", "modest fashion, cooking, poetry", "Runs a hijab styling page"],
  ["Bryce", "UGA", "lacrosse, fishing, country music", "Lacrosse and lake days"],
  ["Chase", "Kennesaw State", "fortnite, basketball, memes", "Fortnite since season 1"],
  ["Delia", "Emory", "psychology, true crime, tea", "Diagnoses serial killers from podcasts"],
  ["Emmett", "Georgia Tech", "linux, open source, retro computers", "Collects old ThinkPads"],
  ["Frankie", "SCAD Atlanta", "tattoos, punk rock, comics", "Designing my own tattoo sleeve"],
  ["Gwen", "Agnes Scott", "environmental science, hiking, podcasts", "Counts salamanders for research"],
  ["Hector", "Georgia State", "boxing, reggaeton, cooking", "Boxes to clear my head"],
  ["Ingrid", "Emory", "scandinavian design, running, coffee", "Swedish exchange student"],
  ["Jonah", "Georgia Tech", "marvel, comics, board games", "Owns every Marvel movie on Blu-ray"],
  ["Kiara", "Clark Atlanta", "mass media, podcasts, fashion", "Hosts a campus podcast"],
  ["Liam", "UGA", "soccer, premier league, fifa", "Arsenal fan, suffering daily"],
  ["Marisol", "Georgia State", "mariachi, singing, cooking", "Sings in a mariachi band"],
  ["Nate", "Kennesaw State", "minecraft, youtube, pizza", "Makes Minecraft videos nobody watches yet"],
  ["Oona", "Agnes Scott", "folk music, banjo, gardening", "Grows my own peppers"],
  ["Pedro", "Emory", "brazilian jiu jitsu, samba, soccer", "From São Paulo, misses the food"],
  ["Rowan", "SCAD Atlanta", "game art, pixel art, indie games", "Making a pixel art platformer"],
  ["Skye", "Georgia Tech", "astronomy, telescopes, sci-fi books", "Stays up for every meteor shower"],
  ["Terrence", "Morehouse", "debate, politics, basketball", "Student government president"],
  ["Violet", "UGA", "interior design, pinterest, coffee", "Redecorates my dorm monthly"],
  ["Wyatt", "Kennesaw State", "hunting, trucks, country music", "Lifted truck, lowered expectations"],
  ["Asher", "Emory", "jewish history, comedy, basketball", "Does standup at open mics"],
  ["Bree", "Georgia State", "hair braiding, r&b, fashion", "Braids hair to pay for textbooks"],
  ["Cyrus", "Georgia Tech", "persian food, chess, ai", "Makes the best tahdig on campus"],
  ["Dina", "Emory", "global health, hiking, cooking", "Spent a summer in Ghana"],
  ["Everett", "UGA", "baseball, country music, bbq", "Braves season ticket holder"],
  ["Freya", "SCAD Atlanta", "norse mythology, illustration, metal music", "Draws Vikings, listens to metal"],
  ["Gus", "Kennesaw State", "disc golf, craft beer, dogs", "My dog comes to every round"],
  ["Helena", "Emory", "opera, italian, classical music", "Soprano in the university opera"],
  ["Ibrahim", "Georgia State", "soccer, arabic calligraphy, tea", "Writes calligraphy for friends"],
  ["Jasper", "Georgia Tech", "hackathons, rust, coffee", "Rewrites everything in Rust"],
  ["Keisha", "Spelman", "entrepreneurship, skincare, gospel", "Selling my own body butter"],
  ["Lorenzo", "Emory", "italian food, soccer, opera", "Makes pasta from scratch weekly"],
  ["Mira", "Georgia Tech", "bioengineering, rock climbing, indie music", "Climbs V6, studies proteins"],
  ["Nolan", "Kennesaw State", "baseball, hunting, country music", "Catcher, knees already hurt"],
  ["Ophelia", "Agnes Scott", "shakespeare, theater, tea", "Played Lady Macbeth twice"],
  ["Pranav", "Georgia Tech", "cricket, ai, bollywood", "Opening batsman on the club team"],
  ["Renee", "Georgia State", "social work, poetry, soul music", "Volunteers at a shelter weekly"],
  ["Soren", "Emory", "philosophy, cycling, coffee", "Reads Kierkegaard for fun"],
  ["Talia", "UGA", "musical theater, dance, broadway", "Tap dances when nervous"],
  ["Ulysses", "Morehouse", "classics, chess, jazz", "Named after the book, read it twice"],
  ["Vera", "SCAD Atlanta", "film photography, vintage, jazz", "Develops film in my bathroom"],
  ["Wade", "UGA", "fishing, bass boats, country music", "Tournament bass fisherman"],
  ["Adele", "Emory", "french, wine, art history", "Spent a semester in Paris"],
  ["Beau", "Kennesaw State", "baseball, trucks, fishing", "Southern charm, northern winters scare me"],
  ["Cassie", "Georgia State", "cheerleading, dance, taylor swift", "Flyer on the cheer team"],
  ["Damon", "Clark Atlanta", "film, screenwriting, hip hop", "Writing a movie about Atlanta"],
  ["Elena", "Georgia Tech", "aerospace, ballet, coffee", "Designs rockets, dances ballet"],
  ["Finn", "UGA", "surfing, sailing, reggae", "Sails every summer at Tybee"],
  ["Gianna", "Kennesaw State", "nursing, softball, country music", "Pitcher turned nursing student"],
  ["Hugo", "Georgia Tech", "formula 1, cars, engineering", "Builds our Formula SAE car"],
  ["Ines", "Emory", "portuguese, soccer, photography", "Photographs every game I go to"],
  ["Jace", "Kennesaw State", "call of duty, energy drinks, basketball", "Warzone every night at 10"],
  ["Kendall", "UGA", "fashion, instagram, pilates", "Outfit posts daily"],
  ["Lionel", "Georgia State", "soccer, messi, fifa", "Named after Messi, obviously"],
  ["Mona", "SCAD Atlanta", "graphic design, zines, coffee", "Makes zines about Atlanta"],
  ["Neel", "Georgia Tech", "competitive programming, chess, cricket", "Codeforces grinder"],
  ["Olive", "Agnes Scott", "gardening, cottagecore, baking", "Bakes sourdough every Sunday"],
  ["Pablo", "Georgia State", "guitar, flamenco, cooking", "Plays flamenco guitar"],
  ["Raven", "SCAD Atlanta", "goth fashion, horror movies, tarot", "Watches a horror movie every night"],
  ["Silas", "Georgia Tech", "elden ring, dark souls, metal music", "Beat every Souls game hitless"],
  ["Tamara", "Spelman", "chemistry, dance, gospel", "Lab by day, dance team by night"],
  ["Vikram", "Emory", "medicine, cricket, bollywood", "Pre-med with a cricket bat"],
  ["Whitney", "UGA", "sorority life, event planning, country music", "Plans every party on the row"],
  ["Andy", "Georgia Tech", "magic the gathering, board games, pizza", "Commander deck builder"],
  ["Bailey", "Kennesaw State", "dogs, hiking, country music", "Hikes with my golden retriever"],
  ["Colin", "Emory", "rowing, finance, podcasts", "Up at 5 for crew practice"],
  ["Dahlia", "SCAD Atlanta", "floral design, painting, jazz", "Paints flowers I grow"],
  ["Enzo", "Georgia State", "soccer, italian food, cars", "Fixes up old Fiats"],
  ["Faith", "Spelman", "ministry, gospel, journaling", "Leads Bible study on Wednesdays"],
  ["Grayson", "UGA", "college football, golf, country music", "Georgia football is religion"],
  ["Hazel", "Agnes Scott", "environmental science, knitting, folk music", "Knits while hiking, somehow"],
  ["Idris", "Morehouse", "film, photography, jazz", "Shooting a documentary on Atlanta jazz"],
  ["Josie", "Kennesaw State", "volleyball, beach trips, taylor swift", "Beach volleyball every summer"],
  ["Khalil", "Clark Atlanta", "poetry, spoken word, r&b", "Performs at open mics weekly"],
  ["Luna", "SCAD Atlanta", "astrology, painting, indie music", "Asks your sign within 5 minutes"],
  ["Marco", "Georgia Tech", "soccer, pizza, engineering", "Makes Neapolitan pizza at home"],
  ["Nell", "Agnes Scott", "library science, cats, mystery novels", "Reads Agatha Christie on repeat"],
  ["Otis", "Morehouse", "soul music, vinyl, cooking", "Collects soul records"],
  ["Pia", "Emory", "german, techno, cycling", "Misses Berlin techno clubs"],
  ["Reid", "Georgia Tech", "pokemon, card games, anime", "Pokémon card collector since age 6"],
  ["Sage", "Agnes Scott", "yoga, meditation, vegan cooking", "Teaches sunrise yoga"],
  ["Troy", "Kennesaw State", "football, lifting, rap", "Linebacker, gentle giant"],
  ["Val", "Georgia State", "roller skating, disco, fashion", "Skates at the rink every Friday"],
  ["Winston", "Emory", "british history, tea, cricket", "From London, misses proper tea"],
  ["Alma", "Georgia State", "mexican folk dance, cooking, family", "Dances ballet folklórico"],
  ["Bruno", "Georgia Tech", "brazilian food, soccer, formula 1", "Senna fan for life"],
  ["Celeste", "Spelman", "astronomy, poetry, jazz", "Writes poems about stars"],
  ["Deshawn", "Clark Atlanta", "basketball, nba 2k, rap", "Point guard on the club team"],
  ["Eden", "Emory", "jewish culture, baking, musicals", "Bakes challah every Friday"],
  ["Flynn", "Georgia Tech", "sailing, robotics, sci-fi", "Building an autonomous sailboat"],
  ["Greta", "Agnes Scott", "climate activism, cycling, folk music", "Organizes campus climate strikes"],
  ["Hayden", "Kennesaw State", "skateboarding, video games, punk rock", "Skate park regular"],
  ["Ivy", "SCAD Atlanta", "botanical illustration, plants, tea", "Draws every plant I own"],
  ["Jude", "Georgia Tech", "guitar, indie rock, coding", "Plays in a campus band"],
  ["Kat", "Georgia State", "roller derby, punk rock, tattoos", "Jammer on the roller derby team"],
  ["Leon", "Morehouse", "economics, chess, soccer", "Chess club president"],
  ["Maeve", "Emory", "irish history, folk music, hiking", "Plays tin whistle"],
  ["Nikhil", "Georgia Tech", "valorant, cricket, biryani", "Makes the best biryani in the dorm"],
  ["Orla", "Agnes Scott", "poetry, sea swimming, folk music", "Swims in cold water for fun"],
  ["Quincy", "Clark Atlanta", "jazz piano, hip hop, chess", "Jazz pianist, plays chess to relax"],
  ["Rocco", "Kennesaw State", "italian food, boxing, baseball", "Nonna's meatballs are unbeatable"],
  ["Serena", "Georgia State", "tennis, fashion, r&b", "Serves on the tennis team"],
  ["Tobias", "Georgia Tech", "elden ring, lore videos, fantasy books", "Can explain all of Elden Ring's lore"],
  ["Vanessa", "UGA", "pre-law, debate, brunch", "Mock trial captain"],
  ["Walt", "Kennesaw State", "woodworking, bluegrass, fishing", "Builds furniture in my garage"],
  ["Amara", "Spelman", "nigerian food, afrobeats, fashion", "Jollof rice champion"],
  ["Bodhi", "Georgia State", "surfing, meditation, reggae", "Chill is my default setting"],
  ["Clara", "Emory", "violin, classical music, baking", "First chair violin"],
  ["Dex", "Georgia Tech", "cyberpunk, synthwave, hacking", "Lives in 2077 mentally"],
  ["Esme", "SCAD Atlanta", "fashion illustration, vintage, jazz", "Sketches outfits on the train"],
  ["Fernando", "Georgia State", "soccer, mexican food, fifa", "Makes tacos al pastor for the team"],
  ["Gemma", "Emory", "british tv, baking, tea", "Great British Bake Off superfan"],
  ["Hollis", "UGA", "bird dogs, hunting, bluegrass", "Trains bird dogs"],
  ["Ren", "Georgia Tech", "genshin impact, anime, cosplay", "Cosplays at DragonCon every year"],
  ["Juno", "Agnes Scott", "astronomy, sci-fi books, tea", "Named after the spacecraft"],
  ["Kwame", "Morehouse", "ghanaian food, soccer, afrobeats", "Hosts jollof debates"],
  ["Lila", "Kennesaw State", "horseback riding, country music, baking", "Rides every weekend"],
  ["Magnus", "Georgia Tech", "chess, viking history, lifting", "Named after Carlsen, can't beat him"],
  ["Nova", "SCAD Atlanta", "3d animation, sci-fi, video games", "Animating a short sci-fi film"],
  ["Omari", "Clark Atlanta", "basketball, sneakers, music production", "Produces for local rappers"],
  ["Poppy", "Agnes Scott", "flower farming, baking, folk music", "Grows sunflowers for the market"],
  ["Rashid", "Georgia State", "soccer, poetry, coffee", "Writes poetry in Arabic and English"],
  ["Stella", "Emory", "astronomy, running, indie music", "Runs at night to see the stars"],
  ["Tate", "UGA", "college football, fishing, country music", "Lives for Saturdays in Athens"],
  ["Vada", "Spelman", "chemistry, braiding, gospel", "Braids hair between lab reports"],
  ["Wiley", "Kennesaw State", "bass fishing, trucks, bbq", "Smokes brisket for the whole dorm"],
  ["Aurora", "SCAD Atlanta", "fantasy art, dnd, tea", "Draws everyone's DnD characters"],
  ["Boris", "Georgia Tech", "chess, russian literature, lifting", "Reads Dostoevsky at the gym"],
  ["Coco", "Georgia State", "fashion, dance, r&b", "Dances in every music video I can"],
];

export const PERSONAS: Persona[] = RAW.map(([name, school, interests, bio], i) => ({
  id: `seed:${i}`,
  name,
  school,
  interests: interests.split(", "),
  bio,
}));
